name: 問題報告
description: 報告本站點相關的問題。請注意閱讀注意事項，否則 issue 將可能被直接關閉。
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        這裡是 Vue.js 3 官方中文 [hk.vuejs.org](https://docs-zh-hk.vercel.app/) 倉庫，僅處理：
        1. 文檔翻譯相關；
        2. 網絡環境和本地化；
        3. 其他與本倉庫直接相關的問題，如譯法討論、流程優化等。

  - type: checkboxes
    id: terms
    attributes:
      label: 提問須知
      description: 請認真閱讀以上說明後，勾選以下字段。
      options:
        - label: 我確定這是官方版本 [hk.vuejs.org](https://docs-zh-hk.vercel.app/) 的 issue，而不是其他非官方翻譯版本
          required: true
        - label: 我確定這是翻譯問題，而不是英文原文的問題 (英文原文的問題請移步至[英文文檔倉庫](https://github.com/vuejs/docs)討論，相關結論我們會定期從英文版同步)
          required: true
        - label: 我確定這不是 Vue.js 使用方面的問題 (此類問題請在 Vue.js 官方的[論壇](https://forum.vuejs.org/c/chinese/7)、[Discord 聊天室](https://chat.vuejs.org/) 或 [StackOverflow](https://stackoverflow.com/tags/vue.js) 上發帖求助)
          required: true

  - type: dropdown
    id: issuetype
    attributes:
      label: 問題類型
      description: 請選擇本 issue 所涉及的問題類型。
      options:
        - 文檔翻譯相關
        - 網絡環境和本地化
        - 譯法討論
        - 流程優化
        - 其他
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: 問題描述
      description: 請描述問題，**截圖+有效鏈接更佳**。
    validations:
      required: true

